name: check
on: push
jobs:
    main:
        runs-on: ubuntu-latest
        steps:
            - name: make-setup
              run: make setup
            - name: make-test
              run: make test
            - name: make-lint
              run: make lint