name: check
on: push
jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - name: make-setup
              run: make setup
            - name: make-test
              run: make test
            - name: make-lint
              run: make lint