name: check
on: push
env: 
    CI: true
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - run: make setup
            - run: make start
            - run: make test
            - run: make lint